/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Frontend;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class AddEntryDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddEntryDialog
     */
    public AddEntryDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocation(parent.getLocation());
    }
    
    public boolean showDialog() {
        this.initDialog();
        this.setVisible(true);
        return this.entryReady;
    }
    
    private void initDialog() {
        this.entryReady = false;
        this.mainPanel_amount.setText("");
        this.mainPanel_tag.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        type = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        mainPanel_Title = new javax.swing.JLabel();
        mainPanel_amountDescription = new javax.swing.JLabel();
        mainPanel_amount = new javax.swing.JTextField();
        mainPanel_tag = new javax.swing.JTextField();
        mainPanel_tagDescription = new javax.swing.JLabel();
        mainPanel_add = new javax.swing.JButton();
        mainPanel_cancel = new javax.swing.JButton();
        mainPanel_radio_income = new javax.swing.JRadioButton();
        mainPanel_radio_expense = new javax.swing.JRadioButton();
        mainPanel_iconBack = new javax.swing.JPanel();
        mainPanel_icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(198, 220, 186));

        mainPanel_Title.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        mainPanel_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainPanel_Title.setText("Add Entry Dialog");

        mainPanel_amountDescription.setText("Specify an amount");

        mainPanel_amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mainPanel_amountKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mainPanel_amountKeyTyped(evt);
            }
        });

        mainPanel_tag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPanel_tagActionPerformed(evt);
            }
        });
        mainPanel_tag.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mainPanel_tagKeyTyped(evt);
            }
        });

        mainPanel_tagDescription.setText("Specify a tag");

        mainPanel_add.setBackground(new java.awt.Color(179, 163, 152));
        mainPanel_add.setText("Add");
        mainPanel_add.setBorder(null);
        mainPanel_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPanel_addActionPerformed(evt);
            }
        });

        mainPanel_cancel.setBackground(new java.awt.Color(179, 163, 152));
        mainPanel_cancel.setText("Cancel");
        mainPanel_cancel.setBorder(null);
        mainPanel_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPanel_cancelActionPerformed(evt);
            }
        });

        type.add(mainPanel_radio_income);
        mainPanel_radio_income.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mainPanel_radio_income.setSelected(true);
        mainPanel_radio_income.setText("Income");
        mainPanel_radio_income.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPanel_radio_incomeActionPerformed(evt);
            }
        });

        type.add(mainPanel_radio_expense);
        mainPanel_radio_expense.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mainPanel_radio_expense.setText("Expense");
        mainPanel_radio_expense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPanel_radio_expenseActionPerformed(evt);
            }
        });

        mainPanel_iconBack.setBackground(new java.awt.Color(220, 255, 183));
        mainPanel_iconBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mainPanel_icon.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        mainPanel_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainPanel_icon.setText("+");

        javax.swing.GroupLayout mainPanel_iconBackLayout = new javax.swing.GroupLayout(mainPanel_iconBack);
        mainPanel_iconBack.setLayout(mainPanel_iconBackLayout);
        mainPanel_iconBackLayout.setHorizontalGroup(
            mainPanel_iconBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        mainPanel_iconBackLayout.setVerticalGroup(
            mainPanel_iconBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(mainPanel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(mainPanel_tagDescription)
                                .addGap(18, 18, 18)
                                .addComponent(mainPanel_tag))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(mainPanel_add, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mainPanel_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(mainPanel_amountDescription)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mainPanel_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mainPanel_radio_expense)
                                    .addComponent(mainPanel_radio_income))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mainPanel_iconBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel_Title)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(mainPanel_radio_income, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainPanel_radio_expense))
                    .addComponent(mainPanel_iconBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainPanel_amountDescription)
                    .addComponent(mainPanel_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainPanel_tagDescription)
                    .addComponent(mainPanel_tag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainPanel_add, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainPanel_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainPanel_amountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainPanel_amountKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mainPanel_amountKeyPressed

    private void mainPanel_tagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPanel_tagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainPanel_tagActionPerformed

    private void mainPanel_amountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainPanel_amountKeyTyped
        if(!Character.isDigit(evt.getKeyChar()))
        {
            if(this.mainPanel_amount.getText().contains(".") ||
                    evt.getKeyChar() != '.')
                evt.consume();
        } 
    }//GEN-LAST:event_mainPanel_amountKeyTyped

    private void mainPanel_tagKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainPanel_tagKeyTyped
        if(!Character.isLetterOrDigit(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_mainPanel_tagKeyTyped

    private void mainPanel_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPanel_cancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_mainPanel_cancelActionPerformed

    private void mainPanel_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPanel_addActionPerformed
        try {
            this.amount = Double.parseDouble(this.mainPanel_amount.getText());
            
            if(this.mainPanel_radio_expense.isSelected())
                this.amount *= -1;
            
            this.tag = this.mainPanel_tag.getText();
            
            if(this.tag.isBlank()) {
                this.tag = "<No tag>";
            }
            
            this.entryReady = isEntryReady();
            
        } catch (NumberFormatException e) {
            System.err.println("Invalid amount: " + e);
            JOptionPane.showMessageDialog(
                    null,
                    "Error: " + e.getMessage(),
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
        
        this.setVisible(false);
    }//GEN-LAST:event_mainPanel_addActionPerformed

    private void mainPanel_radio_incomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPanel_radio_incomeActionPerformed
        // TODO add your handling code here:
        this.mainPanel_icon.setText("+");
        this.mainPanel_iconBack.setBackground(new Color(220, 255, 183));
    }//GEN-LAST:event_mainPanel_radio_incomeActionPerformed

    private void mainPanel_radio_expenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPanel_radio_expenseActionPerformed
        this.mainPanel_icon.setText("-");
        this.mainPanel_iconBack.setBackground(new Color(255, 104, 104));
    }//GEN-LAST:event_mainPanel_radio_expenseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEntryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEntryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEntryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEntryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddEntryDialog dialog = new AddEntryDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.showDialog();
            }
        });
    }
    
    private boolean isEntryReady() {
        return this.amount != 0 && !this.tag.isBlank();
    }

    private boolean entryReady;
    protected double amount;
    protected String tag;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel mainPanel_Title;
    private javax.swing.JButton mainPanel_add;
    private javax.swing.JTextField mainPanel_amount;
    private javax.swing.JLabel mainPanel_amountDescription;
    private javax.swing.JButton mainPanel_cancel;
    private javax.swing.JLabel mainPanel_icon;
    private javax.swing.JPanel mainPanel_iconBack;
    private javax.swing.JRadioButton mainPanel_radio_expense;
    private javax.swing.JRadioButton mainPanel_radio_income;
    private javax.swing.JTextField mainPanel_tag;
    private javax.swing.JLabel mainPanel_tagDescription;
    private javax.swing.ButtonGroup type;
    // End of variables declaration//GEN-END:variables
}
