/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author angel
 */
public class CustomView extends javax.swing.JFrame {

    /**
     * Creates new form BackgroundColor
     */
    public CustomView() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.mainPanel_apply.setEnabled(false);
        this.mainPanel_reset.setEnabled(false);
        
        this.resetColors();
    }
    
    public CustomView(Main main) {
        this();
        this.mainWindow = main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        mainPanel_backPreview = new javax.swing.JPanel();
        mainPanel_tablePreview = new javax.swing.JPanel();
        mainPanel_back = new javax.swing.JButton();
        mainPanel_table = new javax.swing.JButton();
        mainPanel_button = new javax.swing.JButton();
        mainPanel_buttonPreview = new javax.swing.JPanel();
        mainPanel_apply = new javax.swing.JButton();
        mainPanel_reset = new javax.swing.JButton();

        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(198, 220, 186));

        mainPanel_backPreview.setBackground(new java.awt.Color(198, 220, 186));
        mainPanel_backPreview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout mainPanel_backPreviewLayout = new javax.swing.GroupLayout(mainPanel_backPreview);
        mainPanel_backPreview.setLayout(mainPanel_backPreviewLayout);
        mainPanel_backPreviewLayout.setHorizontalGroup(
            mainPanel_backPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );
        mainPanel_backPreviewLayout.setVerticalGroup(
            mainPanel_backPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        mainPanel_tablePreview.setBackground(new java.awt.Color(187, 195, 164));
        mainPanel_tablePreview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout mainPanel_tablePreviewLayout = new javax.swing.GroupLayout(mainPanel_tablePreview);
        mainPanel_tablePreview.setLayout(mainPanel_tablePreviewLayout);
        mainPanel_tablePreviewLayout.setHorizontalGroup(
            mainPanel_tablePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );
        mainPanel_tablePreviewLayout.setVerticalGroup(
            mainPanel_tablePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        mainPanel_back.setBackground(new java.awt.Color(179, 163, 152));
        mainPanel_back.setText("Change Background Color");
        mainPanel_back.setBorder(null);

        mainPanel_table.setBackground(new java.awt.Color(179, 163, 152));
        mainPanel_table.setText("Change Tables Color");
        mainPanel_table.setBorder(null);
        mainPanel_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPanel_tableActionPerformed(evt);
            }
        });

        mainPanel_button.setBackground(new java.awt.Color(179, 163, 152));
        mainPanel_button.setText("Change Buttons Color");
        mainPanel_button.setBorder(null);

        mainPanel_buttonPreview.setBackground(new java.awt.Color(179, 163, 152));
        mainPanel_buttonPreview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout mainPanel_buttonPreviewLayout = new javax.swing.GroupLayout(mainPanel_buttonPreview);
        mainPanel_buttonPreview.setLayout(mainPanel_buttonPreviewLayout);
        mainPanel_buttonPreviewLayout.setHorizontalGroup(
            mainPanel_buttonPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );
        mainPanel_buttonPreviewLayout.setVerticalGroup(
            mainPanel_buttonPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        mainPanel_apply.setBackground(new java.awt.Color(179, 163, 152));
        mainPanel_apply.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        mainPanel_apply.setText("Apply");
        mainPanel_apply.setBorder(null);
        mainPanel_apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPanel_applyActionPerformed(evt);
            }
        });

        mainPanel_reset.setBackground(new java.awt.Color(179, 163, 152));
        mainPanel_reset.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        mainPanel_reset.setText("Set Default");
        mainPanel_reset.setBorder(null);
        mainPanel_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPanel_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(mainPanel_back, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(mainPanel_table, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainPanel_backPreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainPanel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainPanel_tablePreview, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainPanel_apply, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(mainPanel_buttonPreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mainPanel_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel_table, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainPanel_back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel_backPreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainPanel_tablePreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainPanel_apply, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainPanel_buttonPreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainPanel_applyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPanel_applyActionPerformed
        // TODO add your handling code here:
        this.actualTable = this.modTable;
        this.actualBack = this.modBack;
        this.actualButton = this.modButton;
        
        this.mainWindow.setTableBackground(this.actualTable);
        this.mainWindow.getShowAllWindow().setBackgroundAll(this.actualTable);
        
        this.mainPanel_apply.setEnabled(false);
    }//GEN-LAST:event_mainPanel_applyActionPerformed

    private void mainPanel_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPanel_resetActionPerformed
        // TODO add your handling code here:
        this.resetColors();
        this.refresh();
    }//GEN-LAST:event_mainPanel_resetActionPerformed

    private void mainPanel_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPanel_tableActionPerformed
        // TODO add your handling code here:
        this.modTable = JColorChooser.showDialog(
                null,
                "Choose a table colour",
                modTable);
        
        this.refresh();
    }//GEN-LAST:event_mainPanel_tableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomView().setVisible(true);
            }
        });
    }
            
    private void refresh() {
        this.mainPanel_backPreview.setBackground(this.modBack);
        this.mainPanel_buttonPreview.setBackground(this.modButton);
        this.mainPanel_tablePreview.setBackground(this.modTable);
        
        this.mainPanel_apply.setEnabled(!this.isChanged());
        this.mainPanel_reset.setEnabled(!this.isDefault());
    }
    
    private boolean isChanged() {
        return this.modTable.equals(this.actualTable)
                && this.modBack.equals(this.actualBack)
                && this.modButton.equals(this.actualButton);
    }
    
    private void resetColors() {
        this.modTable = this.DEFAULT_TABLE;
        this.modBack = this.DEFAULT_BACK;
        this.modButton = this.DEFAULT_BUTTON;
    }
    
    private boolean isDefault() {
        return this.modTable.equals(this.DEFAULT_TABLE)
                && this.modBack.equals(this.DEFAULT_BACK)
                && this.modButton.equals(this.DEFAULT_BUTTON);
    }
    
    private final Color DEFAULT_TABLE = new Color(187,195,164);
    private final Color DEFAULT_BACK = new Color(198,220,186);
    private final Color DEFAULT_BUTTON = new Color(179,163,152);
    
    private Color modTable;
    private Color modBack;
    private Color modButton;
    
    private Color actualTable;
    private Color actualBack;
    private Color actualButton;
    
    private Main mainWindow;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton mainPanel_apply;
    private javax.swing.JButton mainPanel_back;
    private javax.swing.JPanel mainPanel_backPreview;
    private javax.swing.JButton mainPanel_button;
    private javax.swing.JPanel mainPanel_buttonPreview;
    private javax.swing.JButton mainPanel_reset;
    private javax.swing.JButton mainPanel_table;
    private javax.swing.JPanel mainPanel_tablePreview;
    // End of variables declaration//GEN-END:variables
}
