package Frontend;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author angel
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        period = new javax.swing.ButtonGroup();
        wallet = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        main_tabbedPanel_wallet = new javax.swing.JTabbedPane();
        wallet_total_scroll = new javax.swing.JScrollPane();
        wallet_total_list = new javax.swing.JTable();
        wallet_income_scroll = new javax.swing.JScrollPane();
        wallet_income_list = new javax.swing.JTable();
        wallet_expenses_scroll = new javax.swing.JScrollPane();
        wallet_expenses_list = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mainPanel_disclaimer = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        menu_file = new javax.swing.JMenu();
        menu_file_open = new javax.swing.JMenuItem();
        menu_file_sample = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menu_file_import = new javax.swing.JMenuItem();
        menu_file_export = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menu_file_close = new javax.swing.JMenuItem();
        menu_edit = new javax.swing.JMenu();
        menu_edit_add = new javax.swing.JMenuItem();
        menu_edit_clear = new javax.swing.JMenuItem();
        menu_view = new javax.swing.JMenu();
        menu_view_wallet = new javax.swing.JMenu();
        menu_view_wallet_total = new javax.swing.JRadioButtonMenuItem();
        menu_view_wallet_income = new javax.swing.JRadioButtonMenuItem();
        menu_view_wallet_expenses = new javax.swing.JRadioButtonMenuItem();
        menu_view_period = new javax.swing.JMenu();
        menu_view_period_all = new javax.swing.JRadioButtonMenuItem();
        menu_view_period_anual = new javax.swing.JRadioButtonMenuItem();
        menu_view_period_month = new javax.swing.JRadioButtonMenuItem();
        menu_view_period_custom = new javax.swing.JRadioButtonMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menu_view_date = new javax.swing.JCheckBoxMenuItem();
        menu_view_tag = new javax.swing.JCheckBoxMenuItem();
        menu_help = new javax.swing.JMenu();
        menu_help_doc = new javax.swing.JMenuItem();
        menu_help_about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(198, 220, 186));
        mainPanel.setPreferredSize(new java.awt.Dimension(500, 350));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main_tabbedPanel_wallet.setBackground(new java.awt.Color(187, 195, 164));
        main_tabbedPanel_wallet.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        main_tabbedPanel_wallet.setOpaque(true);
        main_tabbedPanel_wallet.setPreferredSize(new java.awt.Dimension(250, 300));
        main_tabbedPanel_wallet.setRequestFocusEnabled(false);
        main_tabbedPanel_wallet.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                main_tabbedPanel_walletStateChanged(evt);
            }
        });

        wallet_total_scroll.setBackground(new java.awt.Color(187, 195, 164));

        wallet_total_list.setBackground(new java.awt.Color(187, 195, 164));
        wallet_total_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Quantity", "Total", "Tag"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        wallet_total_list.setDoubleBuffered(true);
        wallet_total_list.getTableHeader().setReorderingAllowed(false);
        wallet_total_scroll.setViewportView(wallet_total_list);

        main_tabbedPanel_wallet.addTab("Total", wallet_total_scroll);

        wallet_income_scroll.setBackground(new java.awt.Color(187, 195, 164));

        wallet_income_list.setBackground(new java.awt.Color(187, 195, 164));
        wallet_income_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Quantity", "Total", "Tag"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        wallet_income_list.setDoubleBuffered(true);
        wallet_income_list.getTableHeader().setReorderingAllowed(false);
        wallet_income_scroll.setViewportView(wallet_income_list);

        main_tabbedPanel_wallet.addTab("Income", wallet_income_scroll);

        wallet_expenses_list.setBackground(new java.awt.Color(187, 195, 164));
        wallet_expenses_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Quantity", "Total", "Tag"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        wallet_expenses_list.setDoubleBuffered(true);
        wallet_expenses_list.getTableHeader().setReorderingAllowed(false);
        wallet_expenses_scroll.setViewportView(wallet_expenses_list);

        main_tabbedPanel_wallet.addTab("Expenses", wallet_expenses_scroll);

        mainPanel.add(main_tabbedPanel_wallet, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 6, -1, -1));

        jButton1.setBackground(new java.awt.Color(179, 163, 152));
        jButton1.setText("Show All");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        mainPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 312, 100, 32));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("$$$$$$$");
        mainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 232, -1));

        mainPanel_disclaimer.setEditable(false);
        mainPanel_disclaimer.setBackground(new java.awt.Color(198, 220, 186));
        mainPanel_disclaimer.setColumns(1);
        mainPanel_disclaimer.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        mainPanel_disclaimer.setRows(1);
        mainPanel_disclaimer.setTabSize(1);
        mainPanel_disclaimer.setText("Computer-Human Interaction\nÁngel Arróspide Marco");
        mainPanel_disclaimer.setAutoscrolls(false);
        mainPanel_disclaimer.setBorder(null);
        mainPanel_disclaimer.setMaximumSize(new java.awt.Dimension(48, 18));
        mainPanel_disclaimer.setMinimumSize(new java.awt.Dimension(48, 18));
        mainPanel.add(mainPanel_disclaimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 314, 142, 30));

        jButton2.setBackground(new java.awt.Color(179, 163, 152));
        jButton2.setText("Add entries");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        mainPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 160, 36));

        jButton3.setBackground(new java.awt.Color(179, 163, 152));
        jButton3.setText("Delete entry");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        mainPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 160, 36));

        jButton4.setBackground(new java.awt.Color(179, 163, 152));
        jButton4.setText("Modify entry");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        mainPanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 160, 36));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menu.setBackground(new java.awt.Color(187, 195, 164));
        menu.setBorder(null);
        menu.setBorderPainted(false);

        menu_file.setBackground(new java.awt.Color(187, 195, 164));
        menu_file.setText("File");

        menu_file_open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_file_open.setBackground(new java.awt.Color(187, 195, 164));
        menu_file_open.setText("Open");
        menu_file_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_file_openActionPerformed(evt);
            }
        });
        menu_file.add(menu_file_open);

        menu_file_sample.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_file_sample.setBackground(new java.awt.Color(187, 195, 164));
        menu_file_sample.setText("Open sample");
        menu_file_sample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_file_sampleActionPerformed(evt);
            }
        });
        menu_file.add(menu_file_sample);
        menu_file.add(jSeparator1);

        menu_file_import.setBackground(new java.awt.Color(187, 195, 164));
        menu_file_import.setText("Import csv");
        menu_file_import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_file_importActionPerformed(evt);
            }
        });
        menu_file.add(menu_file_import);

        menu_file_export.setBackground(new java.awt.Color(187, 195, 164));
        menu_file_export.setText("Export csv");
        menu_file_export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_file_exportActionPerformed(evt);
            }
        });
        menu_file.add(menu_file_export);
        menu_file.add(jSeparator2);

        menu_file_close.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_file_close.setBackground(new java.awt.Color(187, 195, 164));
        menu_file_close.setText("Close");
        menu_file_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_file_closeActionPerformed(evt);
            }
        });
        menu_file.add(menu_file_close);

        menu.add(menu_file);

        menu_edit.setBackground(new java.awt.Color(187, 195, 164));
        menu_edit.setText("Edit");

        menu_edit_add.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_edit_add.setBackground(new java.awt.Color(187, 195, 164));
        menu_edit_add.setText("Add entries");
        menu_edit_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_edit_addActionPerformed(evt);
            }
        });
        menu_edit.add(menu_edit_add);

        menu_edit_clear.setBackground(new java.awt.Color(187, 195, 164));
        menu_edit_clear.setText("Clear all entries");
        menu_edit.add(menu_edit_clear);

        menu.add(menu_edit);

        menu_view.setBackground(new java.awt.Color(187, 195, 164));
        menu_view.setText("View");

        menu_view_wallet.setBackground(new java.awt.Color(187, 195, 164));
        menu_view_wallet.setText("Wallet");

        wallet.add(menu_view_wallet_total);
        menu_view_wallet_total.setSelected(true);
        menu_view_wallet_total.setText("Total");
        menu_view_wallet_total.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu_view_wallet_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_view_wallet_totalActionPerformed(evt);
            }
        });
        menu_view_wallet.add(menu_view_wallet_total);

        wallet.add(menu_view_wallet_income);
        menu_view_wallet_income.setText("Income");
        menu_view_wallet_income.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_view_wallet_incomeActionPerformed(evt);
            }
        });
        menu_view_wallet.add(menu_view_wallet_income);

        wallet.add(menu_view_wallet_expenses);
        menu_view_wallet_expenses.setText("Expenses");
        menu_view_wallet_expenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_view_wallet_expensesActionPerformed(evt);
            }
        });
        menu_view_wallet.add(menu_view_wallet_expenses);

        menu_view.add(menu_view_wallet);

        menu_view_period.setBackground(new java.awt.Color(187, 195, 164));
        menu_view_period.setText("Period");

        menu_view_period_all.setBackground(new java.awt.Color(187, 195, 164));
        period.add(menu_view_period_all);
        menu_view_period_all.setSelected(true);
        menu_view_period_all.setText("All");
        menu_view_period.add(menu_view_period_all);

        menu_view_period_anual.setBackground(new java.awt.Color(187, 195, 164));
        period.add(menu_view_period_anual);
        menu_view_period_anual.setText("Anual");
        menu_view_period.add(menu_view_period_anual);

        menu_view_period_month.setBackground(new java.awt.Color(187, 195, 164));
        period.add(menu_view_period_month);
        menu_view_period_month.setText("Month");
        menu_view_period.add(menu_view_period_month);

        menu_view_period_custom.setBackground(new java.awt.Color(187, 195, 164));
        period.add(menu_view_period_custom);
        menu_view_period_custom.setText("Custom");
        menu_view_period.add(menu_view_period_custom);

        menu_view.add(menu_view_period);
        menu_view.add(jSeparator3);

        menu_view_date.setBackground(new java.awt.Color(187, 195, 164));
        menu_view_date.setSelected(true);
        menu_view_date.setText("Show date");
        menu_view.add(menu_view_date);

        menu_view_tag.setBackground(new java.awt.Color(187, 195, 164));
        menu_view_tag.setSelected(true);
        menu_view_tag.setText("Show tag");
        menu_view.add(menu_view_tag);

        menu.add(menu_view);

        menu_help.setBackground(new java.awt.Color(187, 195, 164));
        menu_help.setText("Help");

        menu_help_doc.setBackground(new java.awt.Color(187, 195, 164));
        menu_help_doc.setText("Documentation");
        menu_help.add(menu_help_doc);

        menu_help_about.setBackground(new java.awt.Color(187, 195, 164));
        menu_help_about.setText("About");
        menu_help.add(menu_help_about);

        menu.add(menu_help);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void menu_file_importActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_file_importActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_file_importActionPerformed

    private void menu_file_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_file_openActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_file_openActionPerformed

    private void menu_file_sampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_file_sampleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_file_sampleActionPerformed

    private void menu_file_exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_file_exportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_file_exportActionPerformed

    private void menu_file_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_file_closeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_file_closeActionPerformed
    
    private void menu_edit_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_edit_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_edit_addActionPerformed

    private void menu_view_wallet_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_view_wallet_totalActionPerformed
        // TODO add your handling code here:
        this.main_tabbedPanel_wallet.setSelectedComponent(
                this.wallet_total_scroll
        );
    }//GEN-LAST:event_menu_view_wallet_totalActionPerformed

    private void menu_view_wallet_expensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_view_wallet_expensesActionPerformed
        // TODO add your handling code here:
        this.main_tabbedPanel_wallet.setSelectedComponent(
                this.wallet_expenses_scroll
        );
    }//GEN-LAST:event_menu_view_wallet_expensesActionPerformed

    private void menu_view_wallet_incomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_view_wallet_incomeActionPerformed
        // TODO add your handling code here:
        this.main_tabbedPanel_wallet.setSelectedComponent(
                this.wallet_income_scroll
        );
    }//GEN-LAST:event_menu_view_wallet_incomeActionPerformed

    private void main_tabbedPanel_walletStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_main_tabbedPanel_walletStateChanged

        // 0 = Total, 1 = Income, 2 = Expenses
        switch(this.main_tabbedPanel_wallet.getSelectedIndex())
        {
            case -1 -> System.err.print("Error. No tab selected");
            case 0 -> this.menu_view_wallet_total.setSelected(true);
            case 1 -> this.menu_view_wallet_income.setSelected(true);
            case 2 -> this.menu_view_wallet_expenses.setSelected(true);
            default -> System.err.print("Error. Invalid tab selected");
        }
    }//GEN-LAST:event_main_tabbedPanel_walletStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextArea mainPanel_disclaimer;
    private javax.swing.JTabbedPane main_tabbedPanel_wallet;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menu_edit;
    private javax.swing.JMenuItem menu_edit_add;
    private javax.swing.JMenuItem menu_edit_clear;
    private javax.swing.JMenu menu_file;
    private javax.swing.JMenuItem menu_file_close;
    private javax.swing.JMenuItem menu_file_export;
    private javax.swing.JMenuItem menu_file_import;
    private javax.swing.JMenuItem menu_file_open;
    private javax.swing.JMenuItem menu_file_sample;
    private javax.swing.JMenu menu_help;
    private javax.swing.JMenuItem menu_help_about;
    private javax.swing.JMenuItem menu_help_doc;
    private javax.swing.JMenu menu_view;
    private javax.swing.JCheckBoxMenuItem menu_view_date;
    private javax.swing.JMenu menu_view_period;
    private javax.swing.JRadioButtonMenuItem menu_view_period_all;
    private javax.swing.JRadioButtonMenuItem menu_view_period_anual;
    private javax.swing.JRadioButtonMenuItem menu_view_period_custom;
    private javax.swing.JRadioButtonMenuItem menu_view_period_month;
    private javax.swing.JCheckBoxMenuItem menu_view_tag;
    private javax.swing.JMenu menu_view_wallet;
    private javax.swing.JRadioButtonMenuItem menu_view_wallet_expenses;
    private javax.swing.JRadioButtonMenuItem menu_view_wallet_income;
    private javax.swing.JRadioButtonMenuItem menu_view_wallet_total;
    private javax.swing.ButtonGroup period;
    private javax.swing.ButtonGroup wallet;
    private javax.swing.JTable wallet_expenses_list;
    private javax.swing.JScrollPane wallet_expenses_scroll;
    private javax.swing.JTable wallet_income_list;
    private javax.swing.JScrollPane wallet_income_scroll;
    private javax.swing.JTable wallet_total_list;
    private javax.swing.JScrollPane wallet_total_scroll;
    // End of variables declaration//GEN-END:variables
}
